apiVersion: v1
kind: Pod
metadata:
  name: nginx-storage
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-storage
      mountPath: /data/nginx
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["sleep 5000"]
    volumeMounts:
    - name: nginx-storage
      mountPath: /data/nginx
  volumes:
  - name: nginx-storage
    emptyDir: {}
