apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxtest
  name: nginxtest
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginxtest
  template:
    metadata:
      labels:
        app: nginxtest
    spec:
      containers:
      - image: nginx
        name: nginx
