apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpddeploy
  name: httpddeploy
spec:
  replicas: 10
  selector:
    matchLabels:
      app: httpddeploy
  template:
    metadata:
      labels:
        app: httpddeploy
    spec:
      containers:
        - image: httpd:alpine3.18
          name: httpd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
